# Generated by Django 3.2.12 on 2024-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20240228_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
